name: ngnga
description: Next Generation Mobile Client for NGA Forum.

version: 0.2.4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async_redux: ^2.4.2
  business:
    path: ../business/
  built_collection: ^4.3.0
  built_value: ^7.0.0
  cached_network_image: ^2.0.0-rc
  device_info: ^0.4.1+4
  fast_gbk: ^0.1.1+1
  flutter_easyrefresh: ^2.0.8
  flutter_sticky_header: ^0.4.0
  html_unescape: ^1.0.1+3
  image_picker: ^0.6.2+1
  intl: ^0.16.0
  package_info: ^0.4.0+13
  path: ^1.6.4
  path_provider: ^1.5.1
  photo_view: ^0.9.0
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  intl_translation: ^0.17.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/stickers/dark/
    - assets/stickers/light/
  fonts:
    - family: VendorIcon
      fonts:
        - asset: assets/fonts/VendorIcon.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Noto Sans CJK SC
      fonts:
        - asset: assets/fonts/NotoSansCJKsc-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansCJKsc-Medium.otf
          weight: 500
