name: business
description: NGNGA business code.

version: 0.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^2.4.2
  built_collection: ^4.3.0
  built_value: ^7.0.0
  fast_gbk: ^0.1.1+1
  html_unescape: ^1.0.1+3
  http: ^0.12.0+2
  path: ^1.6.4
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  mockito: ^4.1.1
