name: ngnga
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  http: ^0.12.0+2
  path: ^1.6.4
  redux: ^3.0.0
  sqflite: ^1.1.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
