name: ngnga
description: Next Generation Mobile Client for NGA Forum.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^2.1.3
  cupertino_icons: ^0.1.2
  expandable: ^3.0.1
  flutter_widgets: ^0.1.6
  http: ^0.12.0+2
  path: ^1.6.4
  sqflite: ^1.1.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/stickers/
