name: ngnga
description: Next Generation Mobile Client for NGA Forum.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^2.1.3
  cached_network_image: ^1.1.3
  flutter_easyrefresh: ^2.0.4
  flutter_sticky_header: "^0.4.0"
  html_unescape: ^1.0.1+3
  http: ^0.12.0+2
  intl: ^0.16.0
  path_provider: ^1.4.2
  photo_view: ^0.8.0
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stickers/
  fonts:
    - family:  VendorIcon
      fonts:
        - asset: fonts/VendorIcon.ttf
    - family: "Noto Sans CJK SC"
      fonts:
        - asset: fonts/NotoSansCJKsc-Regular.otf
          weight: 400
        - asset: fonts/NotoSansCJKsc-Medium.otf
          weight: 500
