name: ngnga
description: Next Generation Mobile Client for NGA Forum.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^2.1.3
  cached_network_image: ^1.1.3
  cupertino_icons: ^0.1.2
  expandable: ^3.0.1
  flutter_easyrefresh: ^2.0.4
  html_unescape: ^1.0.1+3
  http: ^0.12.0+2
  intl: ^0.16.0
  outline_material_icons: ^0.1.1
  path: ^1.6.4
  photo_view: ^0.8.0
  shared_preferences: ^0.5.4+5
  sqflite: ^1.1.7+2
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stickers/
  fonts:
    - family: "Noto Sans CJK SC"
      fonts:
        - asset: fonts/NotoSansCJKsc-Regular.otf
          weight: 400
        - asset: fonts/NotoSansCJKsc-Medium.otf
          weight: 500
