name: ngnga
description: Next Generation Mobile Client for NGA Forum.

version: 0.0.6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async_redux: ^2.2.0
  cached_network_image: ^1.1.3
  flutter_easyrefresh: ^2.0.4
  flutter_sticky_header: ^0.4.0
  gbk_codec: ^0.3.1+3
  html_unescape: ^1.0.1+3
  http: ^0.12.0+2
  image_picker: ^0.6.2+1
  intl_translation: ^0.17.0
  intl: ^0.15.0
  mockito: ^4.1.1
  path_provider: ^1.4.2
  path: ^1.6.4
  photo_view: ^0.8.0
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stickers/dark/
    - assets/stickers/light/
  fonts:
    - family: VendorIcon
      fonts:
        - asset: assets/fonts/VendorIcon.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Noto Sans CJK SC
      fonts:
        - asset: assets/fonts/NotoSansCJKsc-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansCJKsc-Medium.otf
          weight: 500
