const fs = require("fs");

// wget -O categories.json 'https://bbs.nga.cn/app_api.php?__lib=home&__act=category'
const content = fs.readFileSync("categories.json", "utf-8");
const json = JSON.parse(content);

console.log(`// Auto-generated by etc/categories.js

import 'package:ngnga/models/category.dart';

class CategoryGroup {
  final String name;
  final List<Category> categories;

  const CategoryGroup({this.name, this.categories});
}
`);

console.log("const categoryGroups = [");

for (const group of json.result.map(x => x.groups).flat()) {
  console.log(`CategoryGroup(name: "${group.name}", categories: [`);

  for (const category of group.forums) {
    console.log(`Category(id: ${category.id}, title: "${category.name}"),`)
  }
  console.log(`],),`);
}

console.log("];");
