name: Dev

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Download fonts
        run: |
          wget -q -O assets/fonts/Roboto-Regular.ttf https://github.com/google/fonts/raw/master/apache/roboto/Roboto-Regular.ttf
          wget -q -O assets/fonts/Roboto-Medium.ttf https://github.com/google/fonts/raw/master/apache/roboto/Roboto-Medium.ttf
          wget -q -O assets/fonts/NotoSansCJKsc-Regular.otf https://github.com/googlefonts/noto-cjk/raw/master/NotoSansCJKsc-Regular.otf
          wget -q -O assets/fonts/NotoSansCJKsc-Medium.otf https://github.com/googlefonts/noto-cjk/raw/master/NotoSansCJKsc-Medium.otf

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.12.13+hotfix.5

      - name: test business
        run: |
          cd ${{ github.workspace }}/business
          flutter pub get
          flutter packages pub run build_runner build
          flutter format --set-exit-if-changed lib/ test/
          flutter analyze
          flutter test

      - name: test client
        run: |
          cd ${{ github.workspace }}/client
          flutter pub get
          flutter packages pub run build_runner build
          flutter format --set-exit-if-changed lib/ test/
          flutter analyze
          flutter test
